import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import { toast, Toaster } from 'poply';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Poply</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>Poply</h1>
          <button
            onClick={() =>
              toast.warning('Gratulacje! Udało ci się poprawnie zalogować', {
                duration: 40000,
                position: 'bottom-center',
              })
            }
          >
            Show
          </button>
          <div className={styles.cardRow}></div>
        </div>
      </main>
      <Toaster bgColor="#000" textColor="#fff" />
    </>
  );
};

export default Home;
