import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import { toast, Toaster } from 'poply';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Poply</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>Poply</h1>
          {/* eslint-disable-next-line @typescript-eslint/no-unsafe-call,@typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-return */}
          <button
            onClick={() =>
              toast.warning(`This is a cool dasdsa dasdas, mkkm mdkasmdk`, {
                duration: 200000,
              })
            }
          >
            Show
          </button>
          <div className={styles.cardRow}></div>
        </div>
      </main>
      <Toaster position={'bottom-center'} maxToasts={4} maxToastsPerMessage={2} />
    </>
  );
};

export default Home;
